### ISSUE TITLE
Issue. with Quarterly Cron Schedules

### ISSUE THREAD

**Issue by CharlesAbetz** [P4sca1/cron-schedule#120]
Hi 

This may be a problem with one of your dependancies, not the project itself, as https://crontab.guru seems to have the same problem.

However a sample of the issue.

Start Date of a cron is: 16th May 2021
Cron Expression is: 0 0 16 */3 *

The next list of dates are.
next at 2021-07-16 00:00:00
then at 2021-10-16 00:00:00
then at 2022-01-16 00:00:00
then at 2022-04-16 00:00:00
then at 2022-07-16 00:00:00

This is wrong, it should be August, November, February etc.

If you switch it to 2 or 4, you get correct list of dates.

Regards
Charles

**Comment by P4sca1** [comment]
This project does not use any external dependencies except for development.

The result you get is expected. */3 for the month field is the same as 1-12/3. This means every 3rd months starting from month 1. This will be months 1,4,7,10.

You want months 2,5,8,11 starting at month 2 (February). This can achieved in the following ways:

* Starting the range at February 2-12/3
* Explicitly listing the months 2,5,8,11
* Explicitly listing the months using aliases feb,may,aug,nov

**Comment by P4sca1** [comment]
I hope I was able to help you with your issue. I am closing this issue, because there was no reply for the last 2 weeks.
