### ISSUE TITLE
Cron expression '*/0 * * * *' hangs while parsing

### ISSUE THREAD

**Issue by augustg** [P4sca1/cron-schedule#134]
Passing '*/0 * * * *' to parseCronExpression fails.
Trying it in chrome hangs the current tab. On RunKit evaluation times out.

**Comment by P4sca1** [comment]
Nice catch! Providing a step value of 0 indeed causes an infinite loop. I will add validation for this with the next release.
Im curious though what did you want to achieve with this cron?

**Comment by augustg** [comment]
Wasnt trying to achieve anything. A user input /0 by mistake which hung the UI :).

I have updated the package on my end and confirmed /0 does not cause an infinite loop anymore.
Thank you for fixing it so quickly!
