### ISSUE TITLE
Weekday range to sunday edge case

### ISSUE THREAD

**Issue by sky0hunter** [P4sca1/cron-schedule#282]
Heyho,

there is a little bug when using a range for weekdays which includes sunday as '7', due to the replacement with '0'.

I.e.: `5 10 * * 6-7` will throw `Failed to parse 6-7: Invalid range (start: 6, end: 0).`

**Comment by P4sca1** [comment]
Thank you for raising this. I'm going to have a look at this, once I get some spare time.
