### ISSUE TITLE
Seconds are rounded to 0

### ISSUE THREAD

**Issue by nemanjapetrovic** [P4sca1/cron-schedule#61]
Hi,

It seems I run into some issue or I am doing something wrong.

I have the following code:

```
var cron = require('cron-schedule')
const time = cron.parseCronExpression('*/2 * * * *')
console.log(time.getNextDate(new Date()))
```

This cron should give me 2 minutes after the current date, but somehow the seconds are always rounded to 0. Why is that?
It doesn't take into calculation seconds at all. My guess if you set the date to `2021-01-10 18:12:35.293` you should get `2021-01-10 18:14:35.293` but instead you get the following (seconds rounded to 0).

![image](https://user-images.githubusercontent.com/15672932/104130213-cf571c80-536f-11eb-8700-b8e6b4fd9517.png)

**Comment by P4sca1** [comment]
Hey,

in fact it was a design decision to always set seconds to 0, because seconds are not part of crontab by default.
If you want to have control over seconds, you can prepend another field to the cron string, explicitly specifying the seconds.

```js
const cron = require('cron-schedule')
const time = cronparseCronExpression('10 */2 * * * *')
// This will have seconds 10 instead of 0.
console.log(time.getNextDate())
```

Also, you dont need to specify `new Date()` in `getNextDate()`, as it is the default.

**Comment by P4sca1** [comment]
> This cron should give me 2 minutes after the current date
Just to be clear: It won't give you 2 minutes after the current date. But rather the next even minute after the curent date.
So if minute is 13, it will give you 14 not 15.

**Comment by nemanjapetrovic** [comment]
@P4sca1 

There is no way to somehow just calculate "from this date time give me next time based on cron time"?

**Comment by P4sca1** [comment]
@nemanjapetrovic This is exactly what getNextDate is for. Could you clarify what you want to do and maybe give examples of dates and which results you expect?

**Comment by nemanjapetrovic** [comment]
Sorry, I was a bit confusing above 🤦‍♂️ 

About your response here:

>Just to be clear: It won't give you 2 minutes after the current date. But rather the next even minute after the curent date.
So if minute is 13, it will give you 14 not 15.

why it will give me the even number, that is my question. If I send the time with minute 13 I expect the minute to be 15 if the cron runs every 2 minutes?

**Comment by P4sca1** [comment]
Thats how cron works. */2 is short for 0,2,4,6,8,10,12,....
Similarly you could do 1-59/2 which would be 1,3,5,7,9,11,...
Those numbers represent exact values for hour, minute etc and not values relative to the input date.

If you just want something to run after x minutes, use setTimeout instead.

**Comment by nemanjapetrovic** [comment]
Thank you. I will close this issue.
