### ISSUE TITLE
Cron Job Task Issue

### ISSUE THREAD

**Issue by mkhstar** [P4sca1/cron-schedule#78]
Hi @P4sca1 
It seems the task of the scheduler runs twice when the cron time is due. Is there anything i am doing wrong?

```javascript
function job(){
 console.log('run')
}

const cron = parseCronExpression('*/15 * * * *');

scheduler.setInterval(cron, job);

```

When i run the code above it executes the function job twice every 15 minutes

**Comment by P4sca1** [comment]
Your code looks fine, it shouldn't execute twice. Could you provide a small reproduction script so I can test it? Does it only occur when using every 15 minutes or also when using every minute?

**Comment by P4sca1** [comment]
@mkhstar Another thing that came to my mind is that you may be loading / executing the code twice?

**Comment by mkhstar** [comment]
Hi @P4sca1 
Thanks for replying. Actually i works fine when i use '*/1* * * *' that is every minute. I am trying to replicate the problem on replit

**Comment by P4sca1** [comment]
Okay, would be great to have a reproduction so I can take a look at it.

**Comment by mkhstar** [comment]
Hi @P4sca1 
All of a sudden i have not been observing this issue anymore. It might be a bug in our source code itself. Thanks for your effort

**Comment by degletnour** [comment]
Hello, 

I just had the same issue using the following cron : 0 0 11 * * * 

I didn't witness it before, and I've using cron-schedule for months. 

It seems to be that the circumstances that lead to this bug rarely meet.

**Comment by P4sca1** [comment]
Interesting, are you also using the interval based scheduler?
